### ISSUE TITLE
bug: Import returns unexpected token 'export' error 

### ISSUE THREAD

**Issue by DrMowinckel** [ph-fritsche/react-gapi#2]
When following the example for GoogleApiProvider, rendering fails with the error `SyntaxError: Unexpected token 'export'`.
This also happens when running it in RunKit on npm.

**Expected behavior**
I expected the component to render with the gapi.

**Actual behavior**
Rendering failed with the aforementioned error.

**To Reproduce**
 - Create React NextJS project
 - install react-gapi package
 - import GoogleApiProvider from 'react-gapi'
 - npm run dev

**Environment**
This should at least contain:
 - react-gapi 0.1.2
 - nextjs
 - dotenv

**Code**
```
import { GoogleApiProvider } from 'react-gapi';

const Layout = ({children}) => {
  return (
    <GoogleApiProvider clientId={process.env.DRIVE_API_CLIENT_ID}>
      { children }
    </GoogleApiProvider>
  )
}

export default Layout;
```

**Comment by ph-fritsche** [comment]
Thanks a lot for the report :heart: 
Sorry this issue was hanging for a while. The exports have been misconfigured but worked with some configurations/bundlers. :shrug: 

The exports in [v1.0.0-alpha.6](https://github.com/ph-fritsche/react-gapi/releases/tag/v1.0.0-alpha.6) should work with common bundlers, node and tsc.

**Comment by Johannes5** [comment]
I seem to have the same issue:

./node_modules/react-gapi/dist/esm/GoogleApiProvider.js 27:38
Module parse failed: Unexpected token (27:38)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     var _options$discoveryDoc, _options$scopes;
| 
>     const modules = (options.modules ?? []).concat(((_options$discoveryDoc = options.discoveryDocs) === null || _options$discoveryDoc === void 0 ? void 0 : _options$discoveryDoc.length) ? ['client'] : [], ((_options$scopes = options.scopes) === null || _options$scopes === void 0 ? void 0 : _options$scopes.length) ? ['auth2'] : []);
| 
|     if (gapi) {

**Comment by ph-fritsche** [comment]
@Johannes5
These are different errors.
The one described in this issue was caused by a bugged export that resulted in a node environment importing [ECMAScript modules](https://nodejs.org/api/esm.html#esm_modules_ecmascript_modules). This resulted in a syntax error as it expected a [CommonJS module](https://nodejs.org/api/modules.html#modules_modules_commonjs_modules) which has no `export` token.

Your issue is the result of your transpiler (babel) not understanding the language version used in the export.
`v1.0.0` is exported as CommonJS modules in `ES5` (primarily for old node environments) and as ECMAScript modules in `ES2020` (for bundlers) syntax.
This includes tokens like null coalesce `??` and optional chaining `?.`.
Depending on your setup you might have to configure additional loaders to support these.
If you are using `react-scripts`, the webpack version does not support these new tokens and with overly-progressive `browserlist` they are not transpiled. See https://github.com/facebook/create-react-app/issues/9468#issuecomment-694191642

**Comment by ph-fritsche** [comment]
Should anyone still have problems importing this library please upgrade to `react-gapi@^1.0.2`. That should work for everyone.
If there are any issues with that (or future) version, please help me fix this by filing a new issue.
